import jsPDF from "jspdf";
import { MedicalAnalysis } from "./types";

/**
 * Service for generating medical prescription PDFs
 */
export class PDFGenerator {
  private doc: jsPDF;
  private yPos: number = 20;

  constructor() {
    this.doc = new jsPDF();
  }

  /**
   * Generate a complete prescription PDF
   */
  static generate(analysis: MedicalAnalysis): void {
    const generator = new PDFGenerator();
    generator.addHeader();
    generator.addPatientInfo(analysis.patientInfo);
    generator.addSOAPNotes(analysis);
    generator.addFooter();
    generator.save();
  }

  /**
   * Add header to PDF
   */
  private addHeader(): void {
    // Title
    this.doc.setFontSize(24);
    this.doc.setTextColor(37, 99, 235);
    this.doc.text("MEDICAL PRESCRIPTION", 105, this.yPos, { align: "center" });

    // Subtitle
    this.yPos += 8;
    this.doc.setFontSize(10);
    this.doc.setTextColor(100, 100, 100);
    this.doc.text(`Date: ${new Date().toLocaleString()}`, 105, this.yPos, {
      align: "center",
    });

    this.yPos += 5;
    this.doc.text("Generated by AI Doctor Assistant", 105, this.yPos, {
      align: "center",
    });

    // Divider line
    this.yPos += 5;
    this.doc.setDrawColor(37, 99, 235);
    this.doc.setLineWidth(0.5);
    this.doc.line(20, this.yPos, 190, this.yPos);

    this.yPos += 10;
  }

  /**
   * Add patient information section
   */
  private addPatientInfo(patientInfo: any): void {
    this.doc.setFontSize(14);
    this.doc.setTextColor(37, 99, 235);
    this.doc.text("PATIENT INFORMATION", 20, this.yPos);

    this.yPos += 7;
    this.doc.setFontSize(10);
    this.doc.setTextColor(0, 0, 0);
    this.doc.text(`Name: ${patientInfo?.name || "N/A"}`, 25, this.yPos);

    this.yPos += 5;
    this.doc.text(`Age: ${String(patientInfo?.age || "N/A")}`, 25, this.yPos);

    this.yPos += 5;
    this.doc.text(
      `Gender: ${String(patientInfo?.gender || "N/A")}`,
      25,
      this.yPos,
    );

    this.yPos += 10;
  }

  /**
   * Add SOAP notes (Subjective, Objective, Assessment, Plan)
   */
  private addSOAPNotes(analysis: MedicalAnalysis): void {
    // S - Subjective (Symptoms)
    this.addSection(
      "S - SUBJECTIVE (Chief Complaints)",
      analysis.symptoms?.join(", ") || "None recorded",
      255,
      193,
      7, // Yellow
    );

    // A - Assessment (Diagnosis)
    this.addSection(
      "A - ASSESSMENT (Diagnosis)",
      analysis.diagnosis || "N/A",
      244,
      67,
      54, // Red
    );

    // P - Plan (Prescription)
    this.addPrescriptionSection(analysis.medications || []);

    // Instructions
    this.addSection(
      "INSTRUCTIONS & FOLLOW-UP",
      analysis.instructions || "Follow prescription as directed",
      156,
      39,
      176, // Purple
    );
  }

  /**
   * Add a colored section to the PDF
   */
  private addSection(
    title: string,
    content: string,
    r: number,
    g: number,
    b: number,
  ): void {
    // Section title
    this.doc.setFontSize(12);
    this.doc.setTextColor(r, g, b);
    this.doc.text(title, 20, this.yPos);

    // Content
    this.yPos += 6;
    this.doc.setFontSize(10);
    this.doc.setTextColor(0, 0, 0);
    const lines = this.doc.splitTextToSize(content, 170);
    this.doc.text(lines, 25, this.yPos);

    this.yPos += lines.length * 5 + 8;
  }

  /**
   * Add prescription medications section
   */
  private addPrescriptionSection(medications: any[]): void {
    this.doc.setFontSize(12);
    this.doc.setTextColor(76, 175, 80); // Green
    this.doc.text("P - PLAN (Prescription)", 20, this.yPos);

    this.yPos += 6;
    this.doc.setFontSize(10);
    this.doc.setTextColor(0, 0, 0);

    if (medications.length === 0) {
      this.doc.text("No medications prescribed", 25, this.yPos);
      this.yPos += 10;
      return;
    }

    medications.forEach((med, index) => {
      // Check if we need a new page
      if (this.yPos > 250) {
        this.doc.addPage();
        this.yPos = 20;
      }

      this.doc.setFont(undefined, "bold");
      this.doc.text(`${index + 1}. ${med.name}`, 25, this.yPos);

      this.doc.setFont(undefined, "normal");
      this.yPos += 5;
      this.doc.text(`    Dosage: ${med.dosage}`, 25, this.yPos);

      this.yPos += 5;
      this.doc.text(`    Frequency: ${med.frequency}`, 25, this.yPos);

      this.yPos += 5;
      this.doc.text(`    Duration: ${med.duration}`, 25, this.yPos);

      this.yPos += 8;
    });

    this.yPos += 4;
  }

  /**
   * Add footer with disclaimer
   */
  private addFooter(): void {
    // Position footer at bottom
    const pageHeight = this.doc.internal.pageSize.height;

    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(20, pageHeight - 20, 190, pageHeight - 20);

    this.doc.setFontSize(8);
    this.doc.setTextColor(120, 120, 120);
    this.doc.text(
      "This prescription was generated using AI assistance. Please verify with a licensed physician.",
      105,
      pageHeight - 13,
      { align: "center" },
    );
    this.doc.text("AI Doctor Assistant | Hackathon 2026", 105, pageHeight - 8, {
      align: "center",
    });
  }

  /**
   * Save the PDF
   */
  private save(): void {
    const filename = `prescription_${Date.now()}.pdf`;
    this.doc.save(filename);
  }
}
